local map = vim.keymap.set
map("n", "<F5>", function()
  require("dap").continue()
end, { desc = "DAP Continue" })
map("n", "<F10>", function()
  require("dap").step_over()
end, { desc = "DAP Step Over" })
map("n", "<F11>", function()
  require("dap").step_into()
end, { desc = "DAP Step Into" })
map("n", "<F12>", function()
  require("dap").step_out()
end, { desc = "DAP Step Out" })
map("n", "<Leader>db", function()
  require("dap").toggle_breakpoint()
end, { desc = "DAP Toggle Breakpoint" })
map("n", "<Leader>dB", function()
  require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "DAP Conditional Breakpoint" })
map("n", "<Leader>dr", function()
  require("dap").repl.toggle()
end, { desc = "DAP REPL" })
map("n", "<Leader>dl", function()
  require("dap").run_last()
end, { desc = "DAP Run Last" })
